Use bytes32 instead of string
api3dao/old-api3-docs pull request #1053
Opened 2022-09-26 13:12 UTC by Anboias

2022-09-26 13:48 UTC, bbenligiray requested changes
It's not clear what `encodedDapiName` is

2022-09-26 13:48 UTC, bbenligiray commented on docs/dapis/developers/data-feed-id-to-reader-to-whitelist-status.md
> +dapiNameHash = ethers.utils.solidityKeccak256(['bytes32'], [encodedDapiName]);
```suggestion
encodedDapiName = ethers.utils.formatBytes32String(dapiName);
dapiNameHash = ethers.utils.solidityKeccak256(['bytes32'], [encodedDapiName]);
```

2022-09-26 13:54 UTC, Anboias commented on docs/dapis/developers/data-feed-id-to-reader-to-whitelist-status.md
> +dapiNameHash = ethers.utils.solidityKeccak256(['bytes32'], [encodedDapiName]);
@bbenligiray, I've rephrased the comment and added an additional step where we encode the dapiName. Would this do?

2022-09-27 07:16 UTC, bbenligiray approved these changes
Yes, looks good

2022-09-27 07:27 UTC, merged