Add migration guides
api3dao/old-api3-docs pull request #1056
Opened 2022-09-26 20:37 UTC by Siegrift

Closes https://github.com/api3dao/airnode/issues/1448

* For the 0.8 migration guide, I copied over the migration guide from @andreogle. See the original slack thread in https://api3workspace.slack.com/archives/C02AYRX8D89/p1663596496939549
* For the 0.9 migration guide, I copied over the content from https://github.com/api3dao/airnode/pull/1461 and also resolved comments from @andreogle

2022-09-27 02:48 UTC, dcroote approved these changes
Nice 👍  only very minor rephrasing suggestions from me.

2022-09-27 02:48 UTC, dcroote commented on docs/airnode/v0.9/reference/migration.md
> +improves cloud provider deployments. The only user facing change is that
Minor
```suggestion
In Airnode v0.9, the `airnode-deployer` underwent an internal refactor to
improve cloud provider deployments. The only user facing change is that
```

2022-09-27 02:48 UTC, dcroote commented on docs/airnode/v0.9/reference/migration.md
> +deployer no longer uses short Airnode address to remove airnode when using the
```suggestion
the deployer no longer uses the short Airnode address to remove an Airnode when executing the
```

2022-09-27 07:14 UTC, Siegrift commented on docs/airnode/v0.9/reference/migration.md
> +deployer no longer uses short Airnode address to remove airnode when using the
I changed it to:
```
The only user facing change is that the deployer
uses the full Airnode address instead of the shortened one when executing the
`remove-with-deployment-details` command
```

as that describes the change better.

2022-09-27 07:16 UTC, dcroote commented on docs/airnode/v0.9/reference/migration.md
> +deployer no longer uses short Airnode address to remove airnode when using the
Yes even better.

2022-09-27 09:48 UTC, Siegrift reviewed
In 0.9. we also have Sepolia network available for Airnodes to use. I don't think this needs to be mentioned in the migration guide though.

2022-09-27 13:37 UTC, wkande approved these changes
I recall @dcroote mentioned some issues with the `0.7.0 to 0.8.0` guide by Andre. I will take a look into them after merging which is when I will add your guides to the sidebars.

- #4 - might be worth mentioning rrp[n].cacheResponses is a new, required field
- #5 (both in the summary and the Details): 0.8.0 uses oisFormat "1.1.1" rather than "1.1.2" (see [here](https://github.com/api3dao/airnode/blob/496bced28f8d495ad5edc55af77d44819dde8b89/packages/airnode-validator/package.json#L26) for example). There is [a bit of debate](https://api3workspace.slack.com/archives/C02AYRX8D89/p1662763603054039) on how to handle the coupling of Airnode and OIS going forward though (for which we might need a 4th opinion :sweat_smile:).
- Minor typo "0.8.9" at the end
- corsOrigins was added for HTTP gateways (relevant config.json changes [here](https://github.com/api3dao/airnode/blob/d199b46dabbe0ccf269c50dae46180505eb80940/packages/airnode-validator/src/config/config.ts#L174-L183)) in [#1357](https://github.com/api3dao/airnode/pull/1357).
- relayRequestId was added as a supported security scheme. Functionality implemented with an example of use in [#1286](https://github.com/api3dao/airnode/pull/1286) (though between that PR and now, OIS was moved into its own repo).

2022-09-27 13:38 UTC, wkande commented on docs/airnode/v0.9/reference/migration.md
> +deployer no longer uses short Airnode address to remove airnode when using the
So is this resolved, @dcroote

2022-09-27 14:44 UTC, dcroote commented
@wkande - Andre incorporated all of my changes before @Siegrift copied it for this PR so all set. 

@Siegrift - I think we should mention Sepolia is available and that we're deprecating some testnets (api3dao/airnode#1476), including why we're doing it. This way we can point users (e.g. from Discord) to one piece of information about the change.

2022-09-27 14:54 UTC, dcroote requested changes
Requesting updates per my above comment

2022-09-28 12:21 UTC, Siegrift commented
> I think we should mention Sepolia is available and that we're deprecating some testnets (https://github.com/api3dao/airnode/pull/1476), including why we're doing it. This way we can point users (e.g. from Discord) to one piece of information about the change.

Ok. Added in last commit. Please either @wkande or @dcroote take a look at wording and make any necessary updates. Feel free to merge it afterwards.

2022-09-28 15:10 UTC, dcroote approved these changes
Thanks @Siegrift. I added a note about Etherscan discontinuing their blockchain explorers and also added these guides to the sidebar nav.

@wkande  I'll leave it to you to merge

2022-09-30 14:40 UTC, merged