Chainapi-import&export-updates
api3dao/old-api3-docs pull request #1078
Opened 2022-10-06 19:10 UTC by RyanMakiola

Made additional changes locally based on https://github.com/api3dao/api3-docs/pull/1070

2022-10-07 13:59 UTC, RyanMakiola commented
latest preview link: https://api3-docs--chainapi-import-export-updates-cjldhdjp.web.app/

2022-10-07 19:42 UTC, wkande commented
@rlt will wait for you to approve this PR before merging.

2022-10-10 12:55 UTC, rlt requested changes
Based on Heikki's comments from earlier, we should probably mention something in the Export section around the difference between copying and downloading.

The actions should be in bold and not in quotes, like on integrations and deployments (and separately we should fix Workspaces)

2022-10-10 12:55 UTC, rlt commented on docs/chainapi/user-guides/Import&Export.md
> +allows you to paste an OIS ([click here](hhttps://docs.api3.org/ois/v1.2/) for
There's a typo here in the url. I wonder if we shouldn't have this in the opening section which is something like "Read more about OIS **here**" instead of hidden in this paragraph.

2022-10-13 07:19 UTC, RyanMakiola commented on docs/chainapi/user-guides/Import&Export.md
> +allows you to paste an OIS ([click here](hhttps://docs.api3.org/ois/v1.2/) for
I think its useful having the link straight after where we mention it, but I think it would be nice to have it in an opening section too for people who later on want to recheck the OIS docs but dont want to go through the docs to find the link. What about having the same link in the opening section and in the paragraph where it is referenced? I have come across documentation that does both and thought it was a nice touch, but if I had to pick one implementation I think the opening section would be best. Another option could be adding a "important links" note that is in padding like I did for important notes, and we have all the links there?

2022-10-13 07:59 UTC, rlt commented on docs/chainapi/user-guides/Import&Export.md
> +allows you to paste an OIS ([click here](hhttps://docs.api3.org/ois/v1.2/) for
I don't agree - by that logic we'd need to include this link in every section of this document where we mention OIS for the first time. Why does it merit a link here but not in the export section? This would get messy quickly. It's also out of context - I tripped over it when I reviewed. It implies you're going to learn more about pasting an OIS, but instead the link takes you to learning about OIS.

I also don't agree about adding an important links bit to every section. This should be once per page, that's pretty common across docs I've read. You could have a read more section in the opening paragraph or at the bottom of the doc.

2022-10-13 11:32 UTC, RyanMakiola commented on docs/chainapi/user-guides/Import&Export.md
> +allows you to paste an OIS ([click here](hhttps://docs.api3.org/ois/v1.2/) for
Happy we go that route then. 
I have made the updates @rlt.

2022-10-13 11:50 UTC, RyanMakiola commented
@rlt just made another change after looking at the review link. Looks fine now for a review.

2022-10-13 12:26 UTC, rlt reviewed
Two minor updates but otherwise this is good to go 👍🏻

2022-10-13 12:26 UTC, rlt commented on docs/chainapi/user-guides/Import&Export.md
> +When exporting, what is the difference between **Download OIS** and **Copy**?
This question style is a bit out of place with the rest of the docs. You could say `In the modal that appears, you have two options to export your OIS:`

2022-10-13 12:26 UTC, rlt commented on docs/chainapi/user-guides/Import&Export.md
> +allows you to paste an OIS for more information) that will be used to
`for more information)` should be removed here

2022-10-13 15:13 UTC, rlt approved these changes

2022-10-14 08:51 UTC, RyanMakiola commented
@wkande this has been approved and is good to be merged.

2022-10-14 13:27 UTC, merged