Add Quintessence QRNG
api3dao/old-api3-docs pull request #1144
Opened 2022-12-08 15:24 UTC by Ashar2shahid

PR Adds Quintessence QRNG info along with information of what chains it serves

2022-12-08 16:35 UTC, wkande requested changes
@Ashar: I think you are missing a testnet for AUN (Goerli) See the **[PR here](https://github.com/api3dao/api3-docs/pull/1137)** where Burak has indicated that ANU does in fact use Goerli.

2022-12-10 02:10 UTC, Ashar2shahid commented
this is what was said in the [PR](https://github.com/api3dao/api3-docs/pull/1137#discussion_r1041869086)
> Previously
ANU: all mainnets and goerli
Now
ANU: all mainnets (and no testnets)
byog: all testnets (and no mainnets)           

according to that this is correct

2022-12-10 23:42 UTC, dcroote approved these changes
Only a minor comment

2022-12-10 23:42 UTC, dcroote commented on docs/qrng/reference/chains.md
> +::: tab BYOG
For consistency:
```suggestion
::: tab byog
```

2022-12-11 22:55 UTC, Ashar2shahid reviewed
Going ahead and merging it

2022-12-13 12:08 UTC, wkande commented
Will be merging this today as soon as I duplicate this into the VitePress docs.

2022-12-13 15:48 UTC, merged