Add airnode-deployer `fetch-files` command
api3dao/old-api3-docs pull request #1161
Opened 2023-01-10 14:41 UTC by amarthadan

Close #1159

2023-01-10 15:44 UTC, dcroote commented
Thanks - will test & review tonight

2023-01-11 05:51 UTC, dcroote requested changes
Looks good overall, I suggest a couple minor language fixes and one slightly more substantive change regarding the output location of the command.

2023-01-11 05:51 UTC, dcroote commented on docs/airnode/v0.10/grp-providers/docker/deployer-image.md
> +which should be the files retrieved. By default, the files from the latest
Typo: "for which should be the files retrieved"

2023-01-11 05:51 UTC, dcroote commented on docs/airnode/v0.10/grp-providers/docker/deployer-image.md
> +version of this deployment are fetched. Additionally, you can provide a
Perhaps "Alternatively" rather than "Additionally" as providing a deployment version ID is an alternative to the default.

2023-01-11 05:51 UTC, dcroote commented on docs/airnode/v0.10/grp-providers/docker/deployer-image.md
> +for the command to run correctly: `aws.env` (for AWS) and/or `gcp.json` (for
I think just "or" rather than "and/or"

2023-01-11 05:51 UTC, dcroote commented on docs/airnode/v0.10/grp-providers/docker/deployer-image.md
> +default, the archive with the files is stored in the `config` directory. You can
I tested the `fetch-files` command and the zip archive got saved to the directory from which I ran the command (`$(pwd)`). Therefore, I would revise this sentence since it pertains to the `config` directory **within the container** and not where the user will actually find the archive.

2023-01-11 08:36 UTC, amarthadan commented on docs/airnode/v0.10/grp-providers/docker/deployer-image.md
> +version of this deployment are fetched. Additionally, you can provide a
I used additionally because you're adding one more argument.
`airnode-deployer fetch-files aws2c6ef2b3 3580a278`
instead of
`airnode-deployer fetch-files aws2c6ef2b3`.
Or maybe it would read better as
`Alternatively, you can additionally provide a...`
Or is that too much? :smile:

2023-01-11 08:38 UTC, amarthadan commented on docs/airnode/v0.10/grp-providers/docker/deployer-image.md
> +default, the archive with the files is stored in the `config` directory. You can
Fair point. Especially since this is the page about the deployer Docker image. Will change.

2023-01-11 08:40 UTC, amarthadan commented on docs/airnode/v0.10/grp-providers/docker/deployer-image.md
> +for the command to run correctly: `aws.env` (for AWS) and/or `gcp.json` (for
I've copied it from the commands above. But it actually makes sense only for the `list` command as that allows you to list deployment from both cloud providers at the same time (hence you can provide authentication for both). I'll fix it for the rest of the commands.

2023-01-11 09:29 UTC, amarthadan commented on docs/airnode/v0.10/grp-providers/docker/deployer-image.md
> +which should be the files retrieved. By default, the files from the latest
I'm probably just blind but what is the typo? :sweat_smile:

2023-01-11 14:53 UTC, dcroote commented on docs/airnode/v0.10/grp-providers/docker/deployer-image.md
> +for the command to run correctly: `aws.env` (for AWS) and/or `gcp.json` (for
Ah for both at the same time- ok nice, never mind then.

2023-01-11 14:54 UTC, dcroote commented on docs/airnode/v0.10/grp-providers/docker/deployer-image.md
> +version of this deployment are fetched. Additionally, you can provide a
I think that could work, but it's a very small nit so will leave up to you

2023-01-11 15:33 UTC, dcroote commented on docs/airnode/v0.10/grp-providers/docker/deployer-image.md
> +default, the archive with the files is stored in the `config` directory. You can
Reads well with your update 👍

2023-01-11 15:38 UTC, dcroote commented on docs/airnode/v0.10/grp-providers/docker/deployer-image.md
> +which should be the files retrieved. By default, the files from the latest
Reworded, I think it should be "for which the files should be retrieved" but a simplified version might just be adjusting earlier in the sentence "...command above to specify the desired deployment."

2023-01-12 06:22 UTC, dcroote approved these changes
Changes look good; the other very minor discussion points are up to you

2023-01-12 12:47 UTC, merged

2023-01-12 13:03 UTC, wkande commented
Deployed