Document OEV gateway
api3dao/old-api3-docs pull request #1227
Opened 2023-03-24 11:19 UTC by Siegrift

In (unreleased) v11 we have added support for OEV gateway, which is needed to OEV relay (for now private).

2023-03-24 11:23 UTC, Siegrift commented on docs/airnode/v0.11/grp-providers/guides/build-an-airnode/http-gateways.md
> +- Pass the correct request body.
I removed this section, because the gateways differ too much and a single table for all of them would be confusing.

2023-03-24 11:25 UTC, Siegrift commented on docs/airnode/v0.11/grp-providers/guides/build-an-airnode/http-gateways.md
> +The OEV gateway request body specifies the payload for the gateway to sign. The
What the gateway does is pretty complex and I don't think it's needed to be explained here. I've mentioned above that the gateway is only meant to be used by OEV relay, so users should not need to call this (but you can say the same for the signed data gateway too 🤷 )

2023-03-24 11:27 UTC, Siegrift reviewed
I tried to search for signed data gateway and modify the sections to include info about OEV gateway. Another change I made was to remove "both/two" and use "all/a few" since we now have 3 gateways.

@wkande It's possible I have missed something that needs update as well.

2023-03-24 11:49 UTC, Siegrift commented on docs/airnode/v0.11/grp-providers/guides/build-an-airnode/oev-gateway.md
> +OEV gateway is used in the OEV flow to sign the data won in the OEV auction. The
I think without more context this is hard to understand for users, so I've added at least a link to learn more about oev.

2023-03-24 11:50 UTC, Siegrift commented on docs/airnode/v0.11/grp-providers/guides/build-an-airnode/oev-gateway.md
> +curl --location '<gatewayUrl>' \
I copied this over from my Postman and I think it's more clear then the previous example.

2023-03-24 17:42 UTC, wkande commented
>I tried to search for signed data gateway and modify the sections to include info about OEV gateway. Another change I made was to remove "both/two" and use "all/a few" since we now have 3 gateways.

@Siegrift I cannot find this change in the 4 files this PR changes. What am I missing

2023-03-24 19:17 UTC, Siegrift commented
> @Siegrift I cannot find this change in the 4 files this PR changes. What am I missing?

That was my comment for an earlier version of the docs. I then noticed that @amarthadan intentionally created a separate document for OEV so I reverted the changes in https://github.com/api3dao/api3-docs/pull/1227/commits/a05ff2f0ada991f4aad07d3e5b408674401f62b2

2023-03-27 06:58 UTC, amarthadan requested changes

2023-03-27 06:58 UTC, amarthadan commented on docs/airnode/v0.11/grp-providers/guides/build-an-airnode/oev-gateway.md
> +  "0xf9ada63d498bca65598b7a2504a89f61a82665dd7e2a0828cf21c6715aca5214103998ac98e5ddc3d32ba50c79de984d286b3d602019acf6689f31845ec04abb1b"
You could have used multiple signatures just to showcase it more :smile:

2023-03-27 06:58 UTC, amarthadan commented on docs/airnode/v0.11/grp-providers/guides/build-an-airnode/oev-gateway.md
> +use it to update the data feed. You can learn more about OEV in
```suggestion
use it to update the data feed. You can learn more about OEV at
```

2023-03-27 06:58 UTC, amarthadan commented on docs/airnode/v0.11/grp-providers/guides/build-an-airnode/monitoring-airnode.md
> +- `signOevReq`: Logs for [OEV gateway requests](./http-gateways.md#oev-gateway)
These links are not correct, are they?

2023-03-27 07:26 UTC, Siegrift commented on docs/airnode/v0.11/grp-providers/guides/build-an-airnode/oev-gateway.md
> +  "0xf9ada63d498bca65598b7a2504a89f61a82665dd7e2a0828cf21c6715aca5214103998ac98e5ddc3d32ba50c79de984d286b3d602019acf6689f31845ec04abb1b"
Yeah, but I think this is good enough. Users won't really need this anyway.

2023-03-27 07:29 UTC, Siegrift commented on docs/airnode/v0.11/grp-providers/guides/build-an-airnode/monitoring-airnode.md
> +- `signOevReq`: Logs for [OEV gateway requests](./http-gateways.md#oev-gateway)
They are. Feel free to test on preview site https://api3-docs--pr1227-document-oev-gw-qxgpiine.web.app/airnode/v0.11/grp-providers/guides/build-an-airnode/monitoring-airnode.html

It will add anchor to the correct section and will scroll it into focus for you.

2023-03-27 07:35 UTC, amarthadan commented on docs/airnode/v0.11/grp-providers/guides/build-an-airnode/monitoring-airnode.md
> +- `signOevReq`: Logs for [OEV gateway requests](./http-gateways.md#oev-gateway)
No, they are not. The OEV link leads to the `http-gateways.html` where it shouldn't. It should lead to `oev-gateway.htm`.

2023-03-27 07:39 UTC, Siegrift commented on docs/airnode/v0.11/grp-providers/guides/build-an-airnode/monitoring-airnode.md
> +- `signOevReq`: Logs for [OEV gateway requests](./http-gateways.md#oev-gateway)
🤦 Oh, I see.

2023-03-27 07:48 UTC, amarthadan approved these changes

2023-03-27 10:35 UTC, patriksimurka approved these changes

2023-03-27 10:49 UTC, wkande approved these changes

2023-03-27 10:49 UTC, wkande commented on docs/airnode/v0.11/grp-providers/guides/build-an-airnode/oev-gateway.md
> +curl --location '<gatewayUrl>' \
Have to trust you on this curl change and it does look good. Does OEV still use the `DapiServer.sol` contract?
```
"dapiServerAddress": "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
```

2023-03-27 10:49 UTC, wkande commented on docs/airnode/v0.11/grp-providers/guides/build-an-airnode/oev-gateway.md
> +OEV gateway is used in the OEV flow to sign the data won in the OEV auction. The
The link is good enough until OEV becomes a reality.

2023-03-27 10:49 UTC, wkande commented on docs/airnode/v0.11/grp-providers/guides/build-an-airnode/http-gateways.md
> +The OEV gateway request body specifies the payload for the gateway to sign. The
So `http-gateways.md` does not appear to be in the list of changed files for this PR. I assume you removed this?

2023-03-27 10:49 UTC, wkande commented on docs/airnode/v0.11/grp-providers/guides/build-an-airnode/http-gateways.md
> +- Pass the correct request body.
Same as a comment I made below about `http-gateways.md`, I assume you remove changes for this file altogether
?

2023-03-27 10:49 UTC, wkande commented on docs/airnode/v0.11/reference/cloud-resources.md
> +| API Gateway     | Endpoints for the Airnode gateways.
This was missing for GCP so I added it using GitHub editor.

**Endpoints for the Airnode gateways.**

2023-03-27 10:54 UTC, merged