Merge the Signed Data gateway in the http-gateways.md doc
api3dao/old-api3-docs pull request #664
Opened 2022-03-09 23:47 UTC by wkande

@amarthadan - So this PR still needs attention to the response section of the `http-gateways.md` doc. The Docker deliver image for dev from the CI was not working. I message Aaron to see if he can help.

I made an assumption that a CURL call for both the HTTP Gateway and the HTTP Signed Data Gateway are the same structure. 

Please preview the preview build show in the comments.

2022-03-10 10:21 UTC, amarthadan requested changes
This looks quite nice to me :+1:
@bbenligiray Can you take a look as well?

2022-03-10 10:21 UTC, amarthadan commented on docs/airnode/v0.5/grp-providers/guides/build-an-airnode/http-gateways.md
> +| &lt;user-defined> | body   | `-d '{"parameters": {"param1": "string", "param2": 5}}'` |
As I wrote you on Slack, there's a difference between the two when it comes to the `parameters` parameter.
HTTP Gateway's is called `parameters` and provides values for the parameters in a JSON object format (like above)
HTTP Signed Data Gateway's is called `encodedParameters` and provides parameters' description in the encoded form, somethkig like `{"encodedParameters": "0x3173737300....000"}`.

2022-03-10 10:21 UTC, amarthadan commented on docs/airnode/v0.5/grp-providers/guides/build-an-airnode/http-gateways.md
> +::::
You can see an example response from the HTTP Signed Data Gateway [here](https://github.com/api3dao/airnode/pull/870#pullrequestreview-893537683). That will most likely change but for now, this is how it looks like.

2022-03-10 10:21 UTC, amarthadan commented on docs/airnode/v0.5/grp-providers/guides/build-an-airnode/http-gateways.md
> +sent from Airnode's [heartbeat](./heartbeat.md) to your specified heartbeat URL.
This is actually a good point. We haven't added the new gateway URL into the heartbeat :sweat_smile: I'm going to do that now and I'll also update the heartbeat docs.

2022-03-11 08:43 UTC, bbenligiray commented on docs/airnode/v0.5/grp-providers/guides/build-an-airnode/http-gateways.md
> +| &lt;user-defined> | body   | `-d '{"parameters": {"param1": "string", "param2": 5}}'` |
In my mind `parameters` always means encoded parameters and you should specify `decodedParameters` when using them.

2022-03-11 12:40 UTC, wkande commented on docs/airnode/v0.5/grp-providers/guides/build-an-airnode/http-gateways.md
> +sent from Airnode's [heartbeat](./heartbeat.md) to your specified heartbeat URL.
I will leave the note about the heartbeat then, thanks

2022-03-11 12:41 UTC, wkande commented on docs/airnode/v0.5/grp-providers/guides/build-an-airnode/http-gateways.md
> +| &lt;user-defined> | body   | `-d '{"parameters": {"param1": "string", "param2": 5}}'` |
It has been changed to `encodedParameters`.

2022-03-11 12:59 UTC, wkande commented
I will change `encodedParameters` back to `parameters` when and fi the code changes.

2022-03-11 13:52 UTC, merged