838 chains.json
api3dao/old-api3-docs pull request #839
Opened 2022-06-24 22:06 UTC by wkande

Closing 838

Please see issue **#838** for questions I have regarding the review of this PR. This PR so far is a single file and I am trying to get the full names (display names) of chains in a single file to reference.

2022-06-25 16:01 UTC, bbenligiray requested changes
So I guess
- Don't need to call mainnets mainnets
- Specify all testnets to be testnets, unless they're Ethereum testnets
- When the testnet has a special name, prepend the project name
- Don't capitalize "Testnet"
Plus a few exceptions to these rules

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "1": { "fullname": "Ethereum Mainnet", "type": "mainnet" },
```suggestion
  "1": { "fullname": "Ethereum", "type": "mainnet" },
```

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "30": { "fullname": "RSK Mainnet", "type": "mainnet" },
```suggestion
  "30": { "fullname": "RSK", "type": "mainnet" },
```

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "31": { "fullname": "RSK Testnet", "type": "testnet" },
```suggestion
  "31": { "fullname": "RSK testnet", "type": "testnet" },
```

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "56": { "fullname": "Binance Smart Chain Mainnet", "type": "mainnet" },
```suggestion
  "56": { "fullname": "BNB Chain", "type": "mainnet" },
```

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "69": { "fullname": "Optimism Kovan", "type": "testnet" },
```suggestion
  "69": { "fullname": "Optimism testnet", "type": "testnet" },
```

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "69": { "fullname": "Optimism Kovan", "type": "testnet" },
Technically it's "Optimistic Kovan" but that is not widely used and will be confusing

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "77": { "fullname": "POA Network Sokol", "type": "mainnet" },
```suggestion
  "77": { "fullname": "POA Network Sokol testnet", "type": "testnet" },
```

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "77": { "fullname": "POA Network Sokol", "type": "mainnet" },
I added Sokol assuming that is the intended testnet for Gnosis Chain. Now I see that there is a Gnosis Chain testnet, so this will be replaced with that at some point.

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "97": { "fullname": "Binance Smart Chain Testnet", "type": "testnet" },
```suggestion
  "97": { "fullname": "BNB Chain testnet", "type": "testnet" },
```

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "137": { "fullname": "Polygon Mainnet", "type": "mainnet" },
```suggestion
  "137": { "fullname": "Polygon", "type": "mainnet" },
```

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "588": { "fullname": "Metis Stardust Testnet", "type": "testnet" },
```suggestion
  "588": { "fullname": "Metis Stardust testnet", "type": "testnet" },
```

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "1088": { "fullname": "Metis Andromeda Mainnet", "type": "testnet" },
```suggestion
  "1088": { "fullname": "Metis Andromeda", "type": "mainnet" },
```

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "4002": { "fullname": "Fantom Testnet", "type": "testnet" },
```suggestion
  "4002": { "fullname": "Fantom testnet", "type": "testnet" },
```

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "2001": { "fullname": "Milkomeda", "type": "mainnet" },
```suggestion
  "2001": { "fullname": "Milkomeda C1", "type": "mainnet" },
```

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "2001": { "fullname": "Milkomeda", "type": "mainnet" },
They will have multiple mainnets

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "43113": { "fullname": "Avalanche Fuji Testnet", "type": "testnet" },
```suggestion
  "43113": { "fullname": "Avalanche Fuji testnet", "type": "testnet" },
```

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "80001": { "fullname": "Mumbai", "type": "mainnet" },
```suggestion
  "80001": { "fullname": "Polygon Mumbai testnet", "type": "testnet" },
```

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "200101": { "fullname": "Milkomeda Testnet", "type": "testnet" },
```suggestion
  "200101": { "fullname": "Milkomeda C1 testnet", "type": "testnet" },
```

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "421611": { "fullname": "Arbitrum Testnet", "type": "testnet" }
```suggestion
  "421611": { "fullname": "Arbitrum testnet", "type": "testnet" }
```

2022-06-25 16:01 UTC, bbenligiray commented on docs/.vuepress/chains.json
> +  "1287": { "fullname": "Moonbase Alpha", "type": "testnet" },
```suggestion
  "1287": { "fullname": "Moonbase Alpha testnet", "type": "testnet" },
```

2022-06-26 04:12 UTC, dcroote commented
I don't have anything additional to add, besides the minor:

I think you want: Closes #838 rather than "Closing 838" for linking this PR to that issue.

2022-06-27 19:03 UTC, merged