Split deployer remove command in two and output receipt.json to config/
api3dao/old-api3-docs pull request #888
Opened 2022-07-11 01:09 UTC by dcroote

Documentation for api3dao/airnode#1322.

Rather than one clunky `remove` command, there are now two remove commands.  `remove-with-receipt` (preferred) uses `receipt.json` while `remove-with-deployment-details` expects the various deployment details instead.

The `receipt.json` default output folder is now `config/` rather than `output/` and therefore all references to the `output/` configuration directory have been removed or replaced, including in the `deploy` command.

2022-07-11 06:38 UTC, amarthadan commented
Please, link the https://github.com/api3dao/api3-docs/issues/855 so it can be closed by merging this PR.

2022-07-11 07:13 UTC, amarthadan requested changes

2022-07-11 07:13 UTC, amarthadan commented on docs/airnode/v0.8/grp-providers/docker/deployer-image.md
>    api3/airnode-deployer:0.7.2 deploy
This is the documentation for v0.8, right? Shouldn't there be a `0.8.0` version (even though not released yet)?

2022-07-11 07:13 UTC, amarthadan commented on docs/airnode/v0.8/reference/packages/deployer.md
> -
Is this no longer needed?

2022-07-11 12:45 UTC, wkande commented
I change the TOC level from 2,3 to 2,4 for `reference > packages > deployer.md`. This way the terms deploy and remove-x will be easier to find in a search.

2022-07-11 12:46 UTC, wkande commented on docs/airnode/v0.8/reference/packages/deployer.md
> -
So is this resolved? @dcroote @amarthadan

2022-07-11 12:52 UTC, amarthadan commented on docs/airnode/v0.8/reference/packages/deployer.md
> -
Not yet, I've asked just this morning...my morning :smile: So, @dcroote is probably asleep and will respond in the morning...his morning :smile:

2022-07-11 14:33 UTC, dcroote commented on docs/airnode/v0.8/grp-providers/docker/deployer-image.md
>    api3/airnode-deployer:0.7.2 deploy
Correct, but @wkande updates all of the version instances when releasing a new version so I didn't update these. @wkande if you'd prefer me update these let me know.

2022-07-11 14:36 UTC, dcroote commented on docs/airnode/v0.8/reference/packages/deployer.md
> -
I augmented the subsequent individual sections on `Airnode Deployment` and `Airnode Removal`, making this redundant.

2022-07-11 19:45 UTC, wkande commented on docs/airnode/v0.8/grp-providers/docker/deployer-image.md
>    api3/airnode-deployer:0.7.2 deploy
@dcroote If you want to change them that is OK. I always double check them when I release. Probably a better workflow than the what I have done in the past to be honest.  I'll hold off the merge.

2022-07-12 01:55 UTC, dcroote commented on docs/airnode/v0.8/grp-providers/docker/deployer-image.md
>    api3/airnode-deployer:0.7.2 deploy
Done! I didn't update links to the v0.8 quick deploy zip files nor to airnode repo files with the v0.8 tag (e.g. (https://github.com/api3dao/airnode/tree/v0.8/packages/...) as neither of these exist yet.

2022-07-12 02:07 UTC, dcroote commented
I updated the version in the deployer commands to `0.8.0` and also linked this PR to the appropriate issue so I think this should now be good to go.

2022-07-12 05:56 UTC, amarthadan approved these changes

2022-07-12 11:20 UTC, merged

2022-07-14 07:53 UTC, martinkolenic commented
Hi @dcroote, I've gone through the package description in the docs and that seems to be okay; however, you might want to link to it from the [Airnode Deployer Image](https://api3-docs--improve-deployer-ux-0soa1cyr.web.app/airnode/v0.8/grp-providers/docker/deployer-image.html) page so that the user can quickly reference it in case they accidentally delete the receipt or something else goes wrong with it. The deployer image page does not mention anything other than this or manual removal, so it might be good to mention that as well.