Update aws.env file handling instructions and docker commands
api3dao/old-api3-docs pull request #891
Opened 2022-07-12 12:06 UTC by vponline

This updates the `aws.env `credentials to be mounted into the docker image as a file (and then exported from there by the deployer) instead of read directly into the container. This allows the `aws.env` file to contain double quotes.

2022-07-13 07:53 UTC, amarthadan commented
Please, link the corresponding issue so it can be closed upon a merge.

2022-07-13 09:40 UTC, vponline commented
> Please, link the corresponding issue so it can be closed upon a merge.

Hmm it should already be linked [here](https://github.com/api3dao/api3-docs/issues/851)  if you mean the 'Linked pull request' field. :confused:

2022-07-13 09:42 UTC, amarthadan commented
> > Please, link the corresponding issue so it can be closed upon a merge.
> 
> Hmm it should already be linked [here](https://github.com/api3dao/api3-docs/issues/851) if you mean the 'Linked pull request' field. confused

I might be going crazy, I would swear it was not there in the morning. Today's not my day :sweat_smile:

2022-07-13 14:53 UTC, dcroote requested changes
Changes requested per https://github.com/api3dao/airnode/issues/1189#issuecomment-1169897970

2022-07-13 14:53 UTC, dcroote commented on docs/airnode/v0.8/grp-providers/docker/deployer-image.md
> +  -v "$(pwd)/output:/app/output" \
This line (and all other lines with `/output` it in this PR) should be removed as the `output/` directory will no longer be used, it will only be `config/`. [See here](https://github.com/api3dao/airnode/issues/1189#issuecomment-1169897970) for more, implemented here in the docs in #888 .

2022-07-13 22:22 UTC, vponline commented on docs/airnode/v0.8/grp-providers/docker/deployer-image.md
> +  -v "$(pwd)/output:/app/output" \
Thanks for checking @dcroote, removed!

2022-07-14 00:55 UTC, dcroote approved these changes
LGTM 👍

2022-07-15 18:27 UTC, wkande approved these changes
Looks good to me.

2022-07-15 18:27 UTC, merged